### ISSUE TITLE
mail.ru support of 

### ISSUE THREAD

**Issue by alibbaba** [lambda81/lambda-addons#12]
Sometimes the mail.ru has url type like this:
http://my.mail.ru/mail/playcine/video/_myvideo/11.html

Which can be played  by modifying url like this :
url = url.replace('/my.mail.ru/mail/', '/api.video.mail.ru/videos/embed/mail/')

Could you please implement this support. Thanks

**Comment by lambda81** [comment]
Sorry for the delay of my reply.
I will add it in next version.
Thank you for your contribution.
