### ISSUE TITLE
Genesis Addon Trakt.tv Pin Auth

### ISSUE THREAD

**Issue by enstine86** [lambda81/lambda-addons#18]
Will you be adding Trakt.tv Pin Authentication to Genesis?  The add on no longer tracks currently playing videos.

**Comment by s7eele** [comment]
hi @enstine86 im looking into this and im hoping you can provide a bit more information:

1. please clarify what you mean by 'no longer tracks currently playing video', im assuming your referring to scrobbling but thought i should make certain
2. are you running the official trakt add-on as well?

**Comment by enstine86** [comment]
Hi @s7eele it looks like Trakt seems to be working for me again.  Yes I had the official trakt add-on running as well.

**Comment by s7eele** [comment]
glad you got it working, sorry it took so long lol
