### ISSUE TITLE
New way of youtube plugin call

### ISSUE THREAD

**Issue by alibbaba** [lambda81/lambda-addons#20]
Can you change youtube plugin call from old method to new one by bromix which is officail kodi youtube addon. So you need to change this line to
https://github.com/lambda81/lambda-addons/blob/master/plugin.video.genesis/default.py#L5325

to ::
plugin://plugin.video.youtube/play/?video_id=%s

If you are wondering, recently,  he add support to Frodo too. Here is the link:
http://forum.kodi.tv/showthread.php?tid=200735&pid=2009854#pid2009854

**Comment by s7eele** [comment]
hi @alibaba, i saw and responded to related post on forum, i understand the issue and im not arguing the validity of your request but i am not clear on what, if any immediate impact it has on the user, i understand errors and/or warnings are seen but i personally verified trailers are still working on both gotham and helix, the forum post suggests it is working in isengaard as well, have you seen or experienced something different?

thx

**Comment by alibbaba** [comment]
Yes, It is working on helix, gotham, and isengard without any problem. But it will be future-proof as the current way is for old youtube call. No, there will be no impact on end user at the moment. I just wanted to make it aware of that as xbmc log shows genesis youtube call method has been deprecated and suggest the new method.
It is not PRIORITY issue. It is just something to mind for future update.

**Comment by s7eele** [comment]
roger that and thx, ill domy best to make sure lambda is aware
