### ISSUE TITLE
Add to Library Feature

### ISSUE THREAD

**Issue by pistiolasm** [lambda81/lambda-addons#23]
I would like to add Greek Shows to the TV Shows library just like on Genesis. http://kinkeadtech.com/2015/03/how-to-merge-kodi-streaming-add-ons-into-the-video-library/

**Comment by s7eele** [comment]
apologies if I've missed it somewhere but which add-on is this for?

**Comment by pistiolasm** [comment]
Hi,
It is for the Hellenic TV addon! Thank you for replying!

Regards,
Miltiadis Pistiolas




On Sat, Jun 6, 2015 at 8:19 PM -0700, "s7eele" <notifications@github.com> wrote:
apologies if I've missed it somewhere but which add-on is this for?

---

**Comment by s7eele** [comment]
no problems, just trying to help where i can, I'll ask him as soon as I get the opportunity, I may have to install it just to be familiar without, might benle to answer if I was more familiar with it, Angel, ttys

**Comment by pistiolasm** [comment]
No problem. If you install both Genesis, and Hellenic TV you will see an option on the Genesis addon that specifies the library location. That is missing from the Hellenic TV addon. Their code is very similar so it will be an easy update.

**Comment by s7eele** [comment]
I was able to ask him a short while ago so good timing but unfortunately I can't say the same for the answer, it appears it is not possible atm, lambdas exact response was:

>3) no, because there isn't any scraper for greek content. there isn't any because there isn't any good database available.

if you could find a reliable scraper I am sure he would consider adding it but it doesn't sound like there is one, if this satisfies your question please close the issue so we can try to keep it clean in here, if you have further questions let me know via reply and I'll help where possible

**Comment by pistiolasm** [comment]
Thank you very much. If I find something I will let you know. I will close this issue for now!

**Comment by s7eele** [comment]
no problems, didn't do much lol
