### ISSUE TITLE
Favorites broken in Genesis

### ISSUE THREAD

**Issue by UberNewf** [lambda81/lambda-addons#32]
See http://forums.tvaddons.ag/threads/33414-quot-Favourites-quot-not-working-in-Genesis-on-Raspberry-Pi-2-OSMC-(ERROR-GetDirectory)

**Comment by UberNewf** [comment]
I've identified when it broke: 4.8.0. It works with 4.5.7. Looks like only 4 files changed between the two:

addon.xml
changelog.txt
default.py
resources/settings.xml

I don't have a clue about Python though so I don't have a suggestion on how to fix.. I hope I've helped in some little way though.

**Comment by fopina** [comment]
I don't use Genesis Favorites as I log in with Trakt account, but I just tested on my OSMC Pi2 with Genesis 4.8.3 and it works

**Comment by UberNewf** [comment]
See http://forums.tvaddons.ag/threads/33414-quot-Favourites-quot-not-working-in-Genesis-on-Raspberry-Pi-2-OSMC-(ERROR-GetDirectory). I've identified it is themes related. I can get it to work too by messing with themes (you will see there as well that other community members are having the same issue).

**Comment by s7eele** [comment]
I just left a response to thread on forum, it sounded like it may have resolved itself from messages on forum but I need to make sure, is it still an issue, if so I will do my best to discuss with lambda

**Comment by UberNewf** [comment]
I commented the thread. As far as I can see, status is "unresolved \ workaround exists".

**Comment by s7eele** [comment]
discussion continues on forum, see thread linked above for more detail but a log has been provided by someone experiencing the issue on OE and Linux, for convenience sake the log can be found at http://xbmclogs.com/pi14lyzk2 

@UberNewf in your last post on the forum you were not able to recreate the issue again, were you able to re-create the issue after clearing the userdata folder I specified?

**Comment by UberNewf** [comment]
Nope. See thread.

The Trakt issue still remains though, after 'clean' repro. I added to that thread too (http://forums.tvaddons.ag/threads/33755-Genesis-4-8-3-Call-to-Trakt-Manager-Add-to-Watchlist-fails-for-TV-Show?p=279318#post279318).

**Comment by s7eele** [comment]
roger that, I'll check out trakt issue shorttly
