### ISSUE TITLE
TV Show Specials/Season 0

### ISSUE THREAD

**Issue by fopina** [lambda81/lambda-addons#39]
Hey, I was just looking into why "Specials" did not show and noticed https://github.com/lambda81/lambda-addons/blob/master/plugin.video.genesis/modules/v4/__init__.py#L3799:

    episodes = [i for i in episodes if not '<SeasonNumber>0</SeasonNumber>' in i]

Any reason why to explicitly discard them? Cosmetics or was it some other issue like lack of sources?

If you let me know why, I wouldn't mind helping

**Comment by lambda81** [comment]
I didn't see this issue before:)
I am not adding them on purpose because most tv shows including popular tv shows don't have any stream available for them.
