### ISSUE TITLE
GENESIS - Latest HD Releases contains cams

### ISSUE THREAD

**Issue by krisawatson** [lambda81/lambda-addons#40]
Previously "Latest HD Releases" only contained DVD quality video's, with the latest releases since 4.8.0 it now contains CAMs.  This is due to switching from movie25 site as the base site for movies to watchfree site which is very basic and doesn't contain filtering for these. I understand that movie25 needs different sites for the different locations but will not be updating genesis until this goes back to use movie25.  

I appreciate all the effort to make an amazing addon for kodi.

**Comment by krisawatson** [comment]
As I cannot create pull requests on your branch. I have created a branch of my own that has your code in it https://github.com/krisawatson/plugin.video.genesis.  It includes an extra option in settings to choose the source website, so I can select movie25 or watchfree.  The main changes are in settings.xml, strings.xml and modules/v4/__init__.py

**Comment by gogorman** [comment]
krisawatson, is there any way you could share the .zip of your version of Genesis.
This fix is exactly what I am looking for, but I know nothing about how to ceate the zip from all of the files.
I tried changing the entries in init.py but I guess you need to compile the changes?
Anyway, if you could help by sharing your most recent version of the compiled .zip that would be amazing!

**Comment by krisawatson** [comment]
Here is the file http://www.filedropper.com/pluginvideogenesis problem is when the plugin gets updated from the lambda repo it gets overridden and you have to keep installing the zip. It's really annoying.  But at least you get proper HD streams.
You will have to go into the genesis settings > Source and choose the movie25.sh as the source

**Comment by gogorman** [comment]
This is fantastic!
Is there a way to stop the automatic update? Perhaps by disabling Kodi auto
updates?
Thanks

**Comment by s7eele** [comment]
I personally wouldnt recommend running ooutdated versions of genesis, especially since this issue is being dealt with in upcoming versions but to answer your question, yes, setting autoupdate to notify will allow you to be notified when updates are available and then you can selectively install those you want while ignoring those you dont, if you want to keep autoupdate enabled you could also disable/remove lambda's repository and that should keep genesis from being updated

**Comment by krisawatson** [comment]
Yea I would prefer not to run older versions of genesis either.  It's just when using the movies section I only ever use the Latest HD Releases and cannot stand to watch cams.  I will continue to use genesis latest versions when this issue is fixed, until then I will use this older version.

Keep up the outstanding work guys. Best plugin for kodi by a country mile.

**Comment by lambda81** [comment]
I am closing this, latest version gets scene releases with no cams anymore.
