### ISSUE TITLE
Genesis Not Working

### ISSUE THREAD

**Issue by joeyv11** [lambda81/lambda-addons#41]
Hello Lambda, I am a big fan of your addons for Kodi. Genesis is the one I use the most and it has been working perfectly, up until 3 days ago? maybe around the same time you did and upgrade?  I have uninstalled and reinstalled many times and still I'm coming up with no search results, script errors,  no streams found, playback failed....and that's some of the error messages I'm getting when I find the content I'm looking for. Most of the time I can't open "latest HD" folders they either don't open or open empty, or on the odd time I can get what I want to work...it will crash half way in. 
Please help. I love your add on and I'm not sure if it's a Kodi thing...or an Addon Thing....I'm new at all this.

**Comment by s7eele** [comment]
hi @joeyv11, genesis is working fine on my end and with others ive checked with, I haven't seen any indication of an issue on the forum either so its extremely unlikely to be a genesis 'issue', my suggestion would be to create a post on the TVADDONS forum where you can find great support for this and all of lambda's other add-ons, if your not already registered you can do so using the follow in link:

http://forums.tvaddons.ag/register.php?referrerid=3871

I think creating a post there is your best bet for solving your issues,  the error messages you are receiving ilead me to believe there are issues above and beyond genesis, if you are registered and you have already posted on the forum please include a link to it in your next comment here on github, if you haven't then register at forum using link above and post your issue in lambdas section of forum, it will receive much more visibility this way also

I can be found on the forum under the same name so if you need something you can pm me, your definitely going to need to upload a log if your getting script errors and crashing, for your convenience im including a link to instructions for uploading a log file http://kodi.wiki/view/Log_file/File_manager_access

your also going to want to provide as much detail as possible including OS, hardware, and versions for everything, let us know if are you encountering any other errors, do any other add-ons fail? do any work? so forth and so on...

one last thing thats kind of a long shot on part of your problem, there are more serious issues to be addressed but where are you located and who is your carrier?

some overseas carriers use a device that filters traffic that can sometimes affect sections of genesis, if your on BT and have a 'homehub' or 'smarthub' you are going to want to disable smart setup, ive never seen this first-hand so I don't know exact details

let me know if you have everything you need to get started on your forum post, ill help however I can so we can close this github issue to make lambda's life a little easier :)

**Comment by joeyv11** [comment]
@S7eele , Thank you so much for your thorough response. I'm running Kodi and TVMC on a Google Nexus Player on my TV and all of the sudden 4 days ago it started crashing, play back errors, script errors and coming up with no search results only half of the time. After reading your response, however, I decided to look at the player itself. I did a factory reset of the Nexus Player and now it's working great like before... Not sure why this happened in the first place and I'm hoping it doesn't happen again...but thanks anyways for getting back so quick and hopefully the good streaming continues.

**Comment by s7eele** [comment]
great news @joeyv11, no problem all BUT can you go ahead and close out this issue? I'm not a github expert but as the creator of the issue you should be able to close it, im just trying to help keep lambdas github clean, save him a little time he can use making genesis even better, thx and ttyl ;)

**Comment by s7eele** [comment]
👍
