### ISSUE TITLE
GENESIS - Trakt account integration fails

### ISSUE THREAD

**Issue by ragusource** [lambda81/lambda-addons#44]
Kodi: 14/15
Genesis: 4.8.5

After adding trakt account details, when I try to load:

 My Genesis > Trakt Collection

Nothing happens, the import trakt options also fail, I see the following error message in the log file:

12:06:23 T:140735269405440   ERROR: GetDirectory - Error getting plugin://plugin.video.genesis/?action=shows_trakt_collection
12:06:23 T:140735269405440   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.genesis/?action=shows_trakt_collection) failed

**Comment by UberNewf** [comment]
Did you sign up for Trakt using the Google or Facebook integration? If so, make sure you add a user name and password inside Trakt (https://trakt.tv/settings) and then use that in Genesis.

**Comment by ragusource** [comment]
Hey,

I did not sign up with Facebook/Google. I am using the username and password that I set from that screen. My username was my email address, I changed this and now it is working fine, maybe it doesn't like special characters.

**Comment by s7eele** [comment]
strange if it just stopped working recently as email/password hasnt worked for authentication in a while, regardless glad to hear you got it working, to make things a bit easier on lambda could you go ahead and close this issue? thx :)

**Comment by ragusource** [comment]
Thanks for the help guys.

**Comment by autbrat** [comment]
I am having this same issue, I was able to get to my user lists before but I had to completely wipe Kodi and start over and now genesis won't import my lists for some reason, this is happening on more than one device, on my computer and also on my MXQ tv box. Please help. Thanks.
