### ISSUE TITLE
Please make tutorial on how to add source

### ISSUE THREAD

**Issue by Thundernerd** [lambda81/lambda-addons#8]
Please make a tutorial of some sorts on how to add a source if someone wants to.
Explaining what function get's called when, what is required etc.

I'd like to add a source myself (KissAnime) to watch more Anime through the Genesis plugin, because Genesis simply is amazing.

Cheers

**Comment by lambda81** [comment]
Sorry for the delay of my reply.
You will have to add a class for it in commonsources, just see the how the rest classes work there.
Then add it in sourceDict in default py
