### ISSUE TITLE
Please add these options:

### ISSUE THREAD

**Issue by SagiTzadik** [lambda81/lambda-addons#9]
Hi lambda! first of all your add-on is amazing and I've created a github account just to write you this comment, sorry if it's in a wrong format or anything like that.

I would really love to see in your plugin the following options:
1. choose how many items you want to see on each page (25 is too little in my opinion. Let the user decide). Should not be a problem imo (just changing count=25 to w\e)
2. Movies & TV shows history-watch-list.
Lets say I am watching a not-so-popular tv show with a long name. Instead of searching for it every time, it would be much easier for the user to find it in the "Last shows you've watched" tab.

Thank you very much for this amazing add-on and keep up the good work!

**Comment by Tazoz** [comment]
I'm guessing you're talking about Genesis. 

In both the movies and TV sections, there are a favourites category. When you find a TV show, you can open the context menu and you will see options to add to library and add to favourites. If you add to favourites, you won't have to search each time you want to watch the show, you'll just go to the favourites section within Genesis.

**Comment by lambda81** [comment]
Sorry for the delay o my reply.

1. I am not loading more that 25 items on each page because this would cause problems to the servers of the databases the addon uses.
2. The addon supports Trakt, Trakt watchlist and progress does exactly what you want:)

**Comment by lambda81** [comment]
Like Tazoz said you can use favourites too, not only Trakt.

**Comment by s7eele** [comment]
@SagiTzadik unless you still have questions can you please close this issue, I'm just trying to help lambda keep things a bit cleaner here, if you still have questions related to this issue please explain

**Comment by s7eele** [comment]
thx!
